### ISSUE TITLE
상품등록 API 요청 오류

### ISSUE THREAD

**Issue by donggov** [qlcid/spring-boot-study#1]
아래와 같이 에러가 발생한다. 원인이 뭘까요?

[nio-8080-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotSupportedException: Content type 'text/plain;charset=UTF-8' not supported]

**Comment by qlcid** [comment]
post로 값을 넘겨줄 때 content-type을 json으로 넘겨야 하는데 text/plain 형식으로 넘겨줬기 때문에 에러가 발생한 것 같습니다.
header의 Content-Type값을 application/json로 설정해주니 제대로 작동했습니다.

**Comment by narvis2** [comment]
어떻게 해결하셧나요??
